package middleware

// Code generated by bud; DO NOT EDIT.

import (
	csrf "github.com/livebud/bud/example/zero/middleware/csrf"
	wraprw "github.com/livebud/bud/example/zero/middleware/wraprw"
	middleware "github.com/livebud/bud/package/middleware"
	http "net/http"
)

type Interface = middleware.Middleware
type Stack = middleware.Stack

func New(
	csrf *csrf.Middleware,
	// session *session.Middleware,
	wraprw *wraprw.Middleware,
) *Middleware {
	return &Middleware{
		csrf,
		// session,
		wraprw,
		Stack{
			wraprw,
			csrf,
			// session,
		},
	}
}

type Middleware struct {
	CSRF *csrf.Middleware
	// Session *session.Middleware
	WrapRW *wraprw.Middleware
	stack  Stack
}

var _ Interface = (*Middleware)(nil)

func (m *Middleware) Middleware(next http.Handler) http.Handler {
	return m.stack.Middleware(next)
}
