package reflector_test

import (
	"errors"
	"reflect"
	"testing"

	"github.com/livebud/bud/pkg/di/internal/reflector"
	"github.com/matryer/is"
)

func idOf(v any) (string, error) {
	return reflector.ID(reflect.TypeOf(v))
}

type customStruct struct {
	Field1 int
	Field2 string
}

type customInterface interface {
	Method1() int
}

type customFunc func() int

type customAlias = int

func TestName(t *testing.T) {
	is := is.New(t)
	name, err := idOf(customStruct{})
	is.NoErr(err)
	is.Equal(name, "github.com/livebud/bud/pkg/di/internal/reflector_test.customStruct")
	name, err = idOf(&customStruct{})
	is.NoErr(err)
	is.Equal(name, "github.com/livebud/bud/pkg/di/internal/reflector_test.*customStruct")
	name, err = idOf(reflect.ValueOf((*customInterface)(nil)).Elem())
	is.NoErr(err)
	is.Equal(name, "reflect.Value")
	name, err = idOf(customFunc(func() int { return 0 }))
	is.NoErr(err)
	is.Equal(name, "github.com/livebud/bud/pkg/di/internal/reflector_test.customFunc")
}

func TestNoName(t *testing.T) {
	is := is.New(t)
	name, err := idOf(bool(false))
	is.True(err != nil)
	is.True(errors.Is(err, reflector.ErrNoName))
	is.Equal(name, "")
	name, err = idOf(int(0))
	is.True(err != nil)
	is.True(errors.Is(err, reflector.ErrNoName))
	is.Equal(name, "")
	name, err = idOf(int8(0))
	is.True(err != nil)
	is.True(errors.Is(err, reflector.ErrNoName))
	is.Equal(name, "")
	name, err = idOf(int16(0))
	is.True(err != nil)
	is.True(errors.Is(err, reflector.ErrNoName))
	is.Equal(name, "")
	name, err = idOf(int32(0))
	is.True(err != nil)
	is.True(errors.Is(err, reflector.ErrNoName))
	is.Equal(name, "")
	name, err = idOf(int64(0))
	is.True(err != nil)
	is.True(errors.Is(err, reflector.ErrNoName))
	is.Equal(name, "")
	name, err = idOf(uint(0))
	is.True(err != nil)
	is.True(errors.Is(err, reflector.ErrNoName))
	is.Equal(name, "")
	name, err = idOf(uint8(0))
	is.True(err != nil)
	is.True(errors.Is(err, reflector.ErrNoName))
	is.Equal(name, "")
	name, err = idOf(uint16(0))
	is.True(err != nil)
	is.True(errors.Is(err, reflector.ErrNoName))
	is.Equal(name, "")
	name, err = idOf(uint32(0))
	is.True(err != nil)
	is.True(errors.Is(err, reflector.ErrNoName))
	is.Equal(name, "")
	name, err = idOf(uint64(0))
	is.True(err != nil)
	is.True(errors.Is(err, reflector.ErrNoName))
	is.Equal(name, "")
	name, err = idOf(uintptr(0))
	is.True(err != nil)
	is.True(errors.Is(err, reflector.ErrNoName))
	is.Equal(name, "")
	name, err = idOf(float32(0))
	is.True(err != nil)
	is.True(errors.Is(err, reflector.ErrNoName))
	is.Equal(name, "")
	name, err = idOf(float64(0))
	is.True(err != nil)
	is.True(errors.Is(err, reflector.ErrNoName))
	is.Equal(name, "")
	name, err = idOf(complex64(0))
	is.True(err != nil)
	is.True(errors.Is(err, reflector.ErrNoName))
	is.Equal(name, "")
	name, err = idOf(complex128(0))
	is.True(err != nil)
	is.True(errors.Is(err, reflector.ErrNoName))
	is.Equal(name, "")
	name, err = idOf(string(""))
	is.True(err != nil)
	is.True(errors.Is(err, reflector.ErrNoName))
	is.Equal(name, "")
	name, err = idOf(byte(0))
	is.True(err != nil)
	is.True(errors.Is(err, reflector.ErrNoName))
	is.Equal(name, "")
	name, err = idOf(rune(0))
	is.True(err != nil)
	is.True(errors.Is(err, reflector.ErrNoName))
	is.Equal(name, "")
	name, err = idOf(errors.New(""))
	is.True(err == nil)
	is.Equal(name, "errors.*errorString")
	name, err = idOf(new(int))
	is.True(err != nil)
	is.True(errors.Is(err, reflector.ErrNoName))
	is.Equal(name, "")
	name, err = idOf(new(int8))
	is.True(err != nil)
	is.True(errors.Is(err, reflector.ErrNoName))
	is.Equal(name, "")
	name, err = idOf(new(int16))
	is.True(err != nil)
	is.True(errors.Is(err, reflector.ErrNoName))
	is.Equal(name, "")
	name, err = idOf(new(int32))
	is.True(err != nil)
	is.True(errors.Is(err, reflector.ErrNoName))
	is.Equal(name, "")
	name, err = idOf(new(int64))
	is.True(err != nil)
	is.True(errors.Is(err, reflector.ErrNoName))
	is.Equal(name, "")
	name, err = idOf(new(uint))
	is.True(err != nil)
	is.True(errors.Is(err, reflector.ErrNoName))
	is.Equal(name, "")
	name, err = idOf(new(uint8))
	is.True(err != nil)
	is.True(errors.Is(err, reflector.ErrNoName))
	is.Equal(name, "")
	name, err = idOf(new(uint16))
	is.True(err != nil)
	is.True(errors.Is(err, reflector.ErrNoName))
	is.Equal(name, "")
	name, err = idOf(new(uint32))
	is.True(err != nil)
	is.True(errors.Is(err, reflector.ErrNoName))
	is.Equal(name, "")
	name, err = idOf(new(uint64))
	is.True(err != nil)
	is.True(errors.Is(err, reflector.ErrNoName))
	is.Equal(name, "")
	name, err = idOf(new(uintptr))
	is.True(err != nil)
	is.True(errors.Is(err, reflector.ErrNoName))
	is.Equal(name, "")
	name, err = idOf(new(float32))
	is.True(err != nil)
	is.True(errors.Is(err, reflector.ErrNoName))
	is.Equal(name, "")
	name, err = idOf(new(float64))
	is.True(err != nil)
	is.True(errors.Is(err, reflector.ErrNoName))
	is.Equal(name, "")
	name, err = idOf(new(complex64))
	is.True(err != nil)
	is.True(errors.Is(err, reflector.ErrNoName))
	is.Equal(name, "")
	name, err = idOf(new(complex128))
	is.True(err != nil)
	is.True(errors.Is(err, reflector.ErrNoName))
	is.Equal(name, "")
	name, err = idOf(new(bool))
	is.True(err != nil)
	is.True(errors.Is(err, reflector.ErrNoName))
	is.Equal(name, "")
	name, err = idOf(new(string))
	is.True(err != nil)
	is.True(errors.Is(err, reflector.ErrNoName))
	is.Equal(name, "")
	name, err = idOf(new(byte))
	is.True(err != nil)
	is.True(errors.Is(err, reflector.ErrNoName))
	is.Equal(name, "")
	name, err = idOf(new(rune))
	is.True(err != nil)
	is.True(errors.Is(err, reflector.ErrNoName))
	is.Equal(name, "")
	name, err = idOf(new(error))
	is.True(err != nil)
	is.True(errors.Is(err, reflector.ErrNoName))
	is.Equal(name, "")
	name, err = idOf(new(interface{}))
	is.True(err != nil)
	is.True(errors.Is(err, reflector.ErrNoName))
	is.Equal(name, "")
	name, err = idOf([]int{})
	is.True(err != nil)
	is.True(errors.Is(err, reflector.ErrNoName))
	is.Equal(name, "")
	name, err = idOf([]int8{})
	is.True(err != nil)
	is.True(errors.Is(err, reflector.ErrNoName))
	is.Equal(name, "")
	name, err = idOf([]int16{})
	is.True(err != nil)
	is.True(errors.Is(err, reflector.ErrNoName))
	is.Equal(name, "")
	name, err = idOf([]int32{})
	is.True(err != nil)
	is.True(errors.Is(err, reflector.ErrNoName))
	is.Equal(name, "")
	name, err = idOf([]int64{})
	is.True(err != nil)
	is.True(errors.Is(err, reflector.ErrNoName))
	is.Equal(name, "")
	name, err = idOf([]uint{})
	is.True(err != nil)
	is.True(errors.Is(err, reflector.ErrNoName))
	is.Equal(name, "")
	name, err = idOf([]uint8{})
	is.True(err != nil)
	is.True(errors.Is(err, reflector.ErrNoName))
	is.Equal(name, "")
	name, err = idOf([]uint16{})
	is.True(err != nil)
	is.True(errors.Is(err, reflector.ErrNoName))
	is.Equal(name, "")
	name, err = idOf([]uint32{})
	is.True(err != nil)
	is.True(errors.Is(err, reflector.ErrNoName))
	is.Equal(name, "")
	name, err = idOf([]uint64{})
	is.True(err != nil)
	is.True(errors.Is(err, reflector.ErrNoName))
	is.Equal(name, "")
	name, err = idOf([]uintptr{})
	is.True(err != nil)
	is.True(errors.Is(err, reflector.ErrNoName))
	is.Equal(name, "")
	name, err = idOf([]float32{})
	is.True(err != nil)
	is.True(errors.Is(err, reflector.ErrNoName))
	is.Equal(name, "")
	name, err = idOf([]float64{})
	is.True(err != nil)
	is.True(errors.Is(err, reflector.ErrNoName))
	is.Equal(name, "")
	name, err = idOf([]complex64{})
	is.True(err != nil)
	is.True(errors.Is(err, reflector.ErrNoName))
	is.Equal(name, "")
	name, err = idOf([]bool{})
	is.True(err != nil)
	is.True(errors.Is(err, reflector.ErrNoName))
	is.Equal(name, "")
	name, err = idOf([]string{})
	is.True(err != nil)
	is.True(errors.Is(err, reflector.ErrNoName))
	is.Equal(name, "")
	name, err = idOf([]byte{})
	is.True(err != nil)
	is.True(errors.Is(err, reflector.ErrNoName))
	is.Equal(name, "")
	name, err = idOf([]rune{})
	is.True(err != nil)
	is.True(errors.Is(err, reflector.ErrNoName))
	is.Equal(name, "")
	name, err = idOf([]error{})
	is.True(err != nil)
	is.True(errors.Is(err, reflector.ErrNoName))
	is.Equal(name, "")
	name, err = idOf([]interface{}{})
	is.True(err != nil)
	is.True(errors.Is(err, reflector.ErrNoName))
	is.Equal(name, "")
	name, err = idOf([1]int{})
	is.True(err != nil)
	is.True(errors.Is(err, reflector.ErrNoName))
	is.Equal(name, "")
	name, err = idOf([1]int8{})
	is.True(err != nil)
	is.True(errors.Is(err, reflector.ErrNoName))
	is.Equal(name, "")
	name, err = idOf([1]int16{})
	is.True(err != nil)
	is.True(errors.Is(err, reflector.ErrNoName))
	is.Equal(name, "")
	name, err = idOf([1]int32{})
	is.True(err != nil)
	is.True(errors.Is(err, reflector.ErrNoName))
	is.Equal(name, "")
	name, err = idOf([1]int64{})
	is.True(err != nil)
	is.True(errors.Is(err, reflector.ErrNoName))
	is.Equal(name, "")
	name, err = idOf([1]uint{})
	is.True(err != nil)
	is.True(errors.Is(err, reflector.ErrNoName))
	is.Equal(name, "")
	name, err = idOf([1]uint8{})
	is.True(err != nil)
	is.True(errors.Is(err, reflector.ErrNoName))
	is.Equal(name, "")
	name, err = idOf([1]uint16{})
	is.True(err != nil)
	is.True(errors.Is(err, reflector.ErrNoName))
	is.Equal(name, "")
	name, err = idOf([1]uint32{})
	is.True(err != nil)
	is.True(errors.Is(err, reflector.ErrNoName))
	is.Equal(name, "")
	name, err = idOf([1]uint64{})
	is.True(err != nil)
	is.True(errors.Is(err, reflector.ErrNoName))
	is.Equal(name, "")
	name, err = idOf([1]uintptr{})
	is.True(err != nil)
	is.True(errors.Is(err, reflector.ErrNoName))
	is.Equal(name, "")
	name, err = idOf([1]float32{})
	is.True(err != nil)
	is.True(errors.Is(err, reflector.ErrNoName))
	is.Equal(name, "")
	name, err = idOf([1]float64{})
	is.True(err != nil)
	is.True(errors.Is(err, reflector.ErrNoName))
	is.Equal(name, "")
	name, err = idOf([1]complex64{})
	is.True(err != nil)
	is.True(errors.Is(err, reflector.ErrNoName))
	is.Equal(name, "")
	name, err = idOf([1]complex128{})
	is.True(err != nil)
	is.True(errors.Is(err, reflector.ErrNoName))
	is.Equal(name, "")
	name, err = idOf([1]bool{})
	is.True(err != nil)
	is.True(errors.Is(err, reflector.ErrNoName))
	is.Equal(name, "")
	name, err = idOf([1]string{})
	is.True(err != nil)
	is.True(errors.Is(err, reflector.ErrNoName))
	is.Equal(name, "")
	name, err = idOf([1]byte{})
	is.True(err != nil)
	is.True(errors.Is(err, reflector.ErrNoName))
	is.Equal(name, "")
	name, err = idOf([1]rune{})
	is.True(err != nil)
	is.True(errors.Is(err, reflector.ErrNoName))
	is.Equal(name, "")
	name, err = idOf([1]error{})
	is.True(err != nil)
	is.True(errors.Is(err, reflector.ErrNoName))
	is.Equal(name, "")
	name, err = idOf([1]interface{}{})
	is.True(err != nil)
	is.True(errors.Is(err, reflector.ErrNoName))
	is.Equal(name, "")
	name, err = idOf(struct{}{})
	is.True(err != nil)
	is.True(errors.Is(err, reflector.ErrNoName))
	is.Equal(name, "")
	name, err = idOf(struct {
		field1 int
		field2 string
	}{})
	is.True(err != nil)
	is.True(errors.Is(err, reflector.ErrNoName))
	is.Equal(name, "")
	name, err = idOf(map[string]int{})
	is.True(err != nil)
	is.True(errors.Is(err, reflector.ErrNoName))
	is.Equal(name, "")
	name, err = idOf(map[string]string{})
	is.True(err != nil)
	is.True(errors.Is(err, reflector.ErrNoName))
	is.Equal(name, "")
	name, err = idOf(map[string]bool{})
	is.True(err != nil)
	is.True(errors.Is(err, reflector.ErrNoName))
	is.Equal(name, "")
	name, err = idOf(map[string]float32{})
	is.True(err != nil)
	is.True(errors.Is(err, reflector.ErrNoName))
	is.Equal(name, "")
	name, err = idOf(map[string]float64{})
	is.True(err != nil)
	is.True(errors.Is(err, reflector.ErrNoName))
	is.Equal(name, "")
	name, err = idOf(map[string]complex64{})
	is.True(err != nil)
	is.True(errors.Is(err, reflector.ErrNoName))
	is.Equal(name, "")
	name, err = idOf(map[string]complex128{})
	is.True(err != nil)
	is.True(errors.Is(err, reflector.ErrNoName))
	is.Equal(name, "")
	name, err = idOf(map[string]interface{}{})
	is.True(err != nil)
	is.True(errors.Is(err, reflector.ErrNoName))
	is.Equal(name, "")
	name, err = idOf(int(42))
	is.True(err != nil)
	is.True(errors.Is(err, reflector.ErrNoName))
	is.Equal(name, "")
	name, err = idOf(float64(42.0))
	is.True(err != nil)
	is.True(errors.Is(err, reflector.ErrNoName))
	is.Equal(name, "")
	name, err = idOf(true)
	is.True(err != nil)
	is.True(errors.Is(err, reflector.ErrNoName))
	is.Equal(name, "")
	name, err = idOf("hello")
	is.True(err != nil)
	is.True(errors.Is(err, reflector.ErrNoName))
	is.Equal(name, "")
	name, err = idOf([]int{1, 2, 3})
	is.True(err != nil)
	is.True(errors.Is(err, reflector.ErrNoName))
	is.Equal(name, "")
	name, err = idOf(customAlias(10))
	is.True(err != nil)
	is.True(errors.Is(err, reflector.ErrNoName))
	is.Equal(name, "")
}
