package env

// Code generated by bud; DO NOT EDIT.

import (
	env "github.com/livebud/bud/example/zero/env"
	runenv "github.com/livebud/bud/example/zero/generator/env"
)

func Load() (*Env, error) {
	var e Env
	// TODO: do this statically instead of using reflect
	if err := runenv.Parse(&e); err != nil {
		return nil, err
	}
	return &e, nil
}

type Env = env.Env
